### ISSUE TITLE
Comic book soundtracks

### ISSUE THREAD

**Issue by SarahMBeecroft** [SarahMBeecroft/Project-1#5]
## User Story
As a user, I want to locate original soundtracks for comic book movies, so I can enjoy them for personal use

## Acceptance Criteria
- [x] index.html has a text input
- [x] index.html has a search button
- [x] link to Spotify API
- [ ] Set up Firebase for data management
- [x] Return Spotify results and link to songs

**Comment by J-Lindley** [comment]
This is done and deployed.
